"""get_horse_master用の変換関数.

KYOSOBA_MASTER2テーブルの出力を統一スキーマに変換する。
"""

import pandas as pd

from keiba_data_interface.schema.columns import HORSE_MASTER_COLUMNS
from keiba_data_interface.schema.types import HORSE_MASTER_TYPES
from keiba_data_interface.utils.dataframe import apply_types, ensure_columns

_COLUMN_MAP: dict[str, str] = {
    "insert_timestamp": "テーブル作成時間",
    "update_timestamp": "テーブル更新時間",
    "record_shubetsu_id": "レコード種別ID",
    "data_kubun": "データ区分",
    "data_sakusei_nengappi": "データ作成年月日",
    "ketto_toroku_bango": "血統登録番号",
    "massho_kubun": "競走馬抹消区分",
    "toroku_nengappi": "競走馬登録年月日",
    "massho_nengappi": "競走馬抹消年月日",
    "seinengappi": "生年月日",
    "bamei": "馬名",
    "bamei_hankaku_kana": "馬名半角ｶﾅ",
    "bamei_eng": "馬名欧字",
    "jra_shisetsu_zaikyu_flag": "JRA施設在きゅうフラグ",
    "umakigo_code": "馬記号コード",
    "seibetsu_code": "性別コード",
    "hinshu_code": "品種コード",
    "moshoku_code": "毛色コード",
    "ketto1_hanshoku_toroku_bango": "父繁殖登録番号",
    "ketto1_bamei": "父馬名",
    "ketto2_hanshoku_toroku_bango": "母繁殖登録番号",
    "ketto2_bamei": "母馬名",
    "ketto3_hanshoku_toroku_bango": "父父繁殖登録番号",
    "ketto3_bamei": "父父馬名",
    "ketto4_hanshoku_toroku_bango": "父母繁殖登録番号",
    "ketto4_bamei": "父母馬名",
    "ketto5_hanshoku_toroku_bango": "母父繁殖登録番号",
    "ketto5_bamei": "母父馬名",
    "ketto6_hanshoku_toroku_bango": "母母繁殖登録番号",
    "ketto6_bamei": "母母馬名",
    "ketto7_hanshoku_toroku_bango": "父父父繁殖登録番号",
    "ketto7_bamei": "父父父馬名",
    "ketto8_hanshoku_toroku_bango": "父父母繁殖登録番号",
    "ketto8_bamei": "父父母馬名",
    "ketto9_hanshoku_toroku_bango": "父母父繁殖登録番号",
    "ketto9_bamei": "父母父馬名",
    "ketto10_hanshoku_toroku_bango": "父母母繁殖登録番号",
    "ketto10_bamei": "父母母馬名",
    "ketto11_hanshoku_toroku_bango": "母父父繁殖登録番号",
    "ketto11_bamei": "母父父馬名",
    "ketto12_hanshoku_toroku_bango": "母父母繁殖登録番号",
    "ketto12_bamei": "母父母馬名",
    "ketto13_hanshoku_toroku_bango": "母母父繁殖登録番号",
    "ketto13_bamei": "母母父馬名",
    "ketto14_hanshoku_toroku_bango": "母母母繁殖登録番号",
    "ketto14_bamei": "母母母馬名",
    "tozai_shozoku_code": "東西所属コード",
    "chokyoshi_code": "調教師コード",
    "chokyoshimei_ryakusho": "調教師名略称",
    "shotai_chiikimei": "招待地域名",
    "seisansha_code": "生産者コード",
    "seisanshamei_hojinkaku_nashi": "生産者名",
    "sanchimei": "産地名",
    "banushi_code": "馬主コード",
    "banushimei_hojinkaku_nashi": "馬主名",
    "heichi_honshokin_ruikei": "平地本賞金累計",
    "shogai_honshokin_ruikei": "障害本賞金累計",
    "heichi_fukashokin_ruikei": "平地付加賞金累計",
    "shogai_fukashokin_ruikei": "障害付加賞金累計",
    "heichi_shutokushokin_ruikei": "平地収得賞金累計",
    "shogai_shutokushokin_ruikei": "障害収得賞金累計",
    "sogo_1chaku": "総合1着",
    "sogo_2chaku": "総合2着",
    "sogo_3chaku": "総合3着",
    "sogo_4chaku": "総合4着",
    "sogo_5chaku": "総合5着",
    "sogo_chakugai": "総合着外",
    "chuo_gokei_1chaku": "中央合計1着",
    "chuo_gokei_2chaku": "中央合計2着",
    "chuo_gokei_3chaku": "中央合計3着",
    "chuo_gokei_4chaku": "中央合計4着",
    "chuo_gokei_5chaku": "中央合計5着",
    "chuo_gokei_chakugai": "中央合計着外",
    "shiba_choku_1chaku": "芝直1着",
    "shiba_choku_2chaku": "芝直2着",
    "shiba_choku_3chaku": "芝直3着",
    "shiba_choku_4chaku": "芝直4着",
    "shiba_choku_5chaku": "芝直5着",
    "shiba_choku_chakugai": "芝直着外",
    "shiba_migi_1chaku": "芝右1着",
    "shiba_migi_2chaku": "芝右2着",
    "shiba_migi_3chaku": "芝右3着",
    "shiba_migi_4chaku": "芝右4着",
    "shiba_migi_5chaku": "芝右5着",
    "shiba_migi_chakugai": "芝右着外",
    "shiba_hidari_1chaku": "芝左1着",
    "shiba_hidari_2chaku": "芝左2着",
    "shiba_hidari_3chaku": "芝左3着",
    "shiba_hidari_4chaku": "芝左4着",
    "shiba_hidari_5chaku": "芝左5着",
    "shiba_hidari_chakugai": "芝左着外",
    "dirt_choku_1chaku": "ダ直1着",
    "dirt_choku_2chaku": "ダ直2着",
    "dirt_choku_3chaku": "ダ直3着",
    "dirt_choku_4chaku": "ダ直4着",
    "dirt_choku_5chaku": "ダ直5着",
    "dirt_choku_chakugai": "ダ直着外",
    "dirt_migi_1chaku": "ダ右1着",
    "dirt_migi_2chaku": "ダ右2着",
    "dirt_migi_3chaku": "ダ右3着",
    "dirt_migi_4chaku": "ダ右4着",
    "dirt_migi_5chaku": "ダ右5着",
    "dirt_migi_chakugai": "ダ右着外",
    "dirt_hidari_1chaku": "ダ左1着",
    "dirt_hidari_2chaku": "ダ左2着",
    "dirt_hidari_3chaku": "ダ左3着",
    "dirt_hidari_4chaku": "ダ左4着",
    "dirt_hidari_5chaku": "ダ左5着",
    "dirt_hidari_chakugai": "ダ左着外",
    "shogai_1chaku": "障害1着",
    "shogai_2chaku": "障害2着",
    "shogai_3chaku": "障害3着",
    "shogai_4chaku": "障害4着",
    "shogai_5chaku": "障害5着",
    "shogai_chakugai": "障害着外",
    "shiba_ryo_1chaku": "芝良1着",
    "shiba_ryo_2chaku": "芝良2着",
    "shiba_ryo_3chaku": "芝良3着",
    "shiba_ryo_4chaku": "芝良4着",
    "shiba_ryo_5chaku": "芝良5着",
    "shiba_ryo_chakugai": "芝良着外",
    "shiba_yayaomo_1chaku": "芝稍1着",
    "shiba_yayaomo_2chaku": "芝稍2着",
    "shiba_yayaomo_3chaku": "芝稍3着",
    "shiba_yayaomo_4chaku": "芝稍4着",
    "shiba_yayaomo_5chaku": "芝稍5着",
    "shiba_yayaomo_chakugai": "芝稍着外",
    "shiba_omo_1chaku": "芝重1着",
    "shiba_omo_2chaku": "芝重2着",
    "shiba_omo_3chaku": "芝重3着",
    "shiba_omo_4chaku": "芝重4着",
    "shiba_omo_5chaku": "芝重5着",
    "shiba_omo_chakugai": "芝重着外",
    "shiba_furyo_1chaku": "芝不1着",
    "shiba_furyo_2chaku": "芝不2着",
    "shiba_furyo_3chaku": "芝不3着",
    "shiba_furyo_4chaku": "芝不4着",
    "shiba_furyo_5chaku": "芝不5着",
    "shiba_furyo_chakugai": "芝不着外",
    "dirt_ryo_1chaku": "ダ良1着",
    "dirt_ryo_2chaku": "ダ良2着",
    "dirt_ryo_3chaku": "ダ良3着",
    "dirt_ryo_4chaku": "ダ良4着",
    "dirt_ryo_5chaku": "ダ良5着",
    "dirt_ryo_chakugai": "ダ良着外",
    "dirt_yayaomo_1chaku": "ダ稍1着",
    "dirt_yayaomo_2chaku": "ダ稍2着",
    "dirt_yayaomo_3chaku": "ダ稍3着",
    "dirt_yayaomo_4chaku": "ダ稍4着",
    "dirt_yayaomo_5chaku": "ダ稍5着",
    "dirt_yayaomo_chakugai": "ダ稍着外",
    "dirt_omo_1chaku": "ダ重1着",
    "dirt_omo_2chaku": "ダ重2着",
    "dirt_omo_3chaku": "ダ重3着",
    "dirt_omo_4chaku": "ダ重4着",
    "dirt_omo_5chaku": "ダ重5着",
    "dirt_omo_chakugai": "ダ重着外",
    "dirt_furyo_1chaku": "ダ不1着",
    "dirt_furyo_2chaku": "ダ不2着",
    "dirt_furyo_3chaku": "ダ不3着",
    "dirt_furyo_4chaku": "ダ不4着",
    "dirt_furyo_5chaku": "ダ不5着",
    "dirt_furyo_chakugai": "ダ不着外",
    "shogai_ryo_1chaku": "障良1着",
    "shogai_ryo_2chaku": "障良2着",
    "shogai_ryo_3chaku": "障良3着",
    "shogai_ryo_4chaku": "障良4着",
    "shogai_ryo_5chaku": "障良5着",
    "shogai_ryo_chakugai": "障良着外",
    "shogai_yayaomo_1chaku": "障稍1着",
    "shogai_yayaomo_2chaku": "障稍2着",
    "shogai_yayaomo_3chaku": "障稍3着",
    "shogai_yayaomo_4chaku": "障稍4着",
    "shogai_yayaomo_5chaku": "障稍5着",
    "shogai_yayaomo_chakugai": "障稍着外",
    "shogai_omo_1chaku": "障重1着",
    "shogai_omo_2chaku": "障重2着",
    "shogai_omo_3chaku": "障重3着",
    "shogai_omo_4chaku": "障重4着",
    "shogai_omo_5chaku": "障重5着",
    "shogai_omo_chakugai": "障重着外",
    "shogai_furyo_1chaku": "障不1着",
    "shogai_furyo_2chaku": "障不2着",
    "shogai_furyo_3chaku": "障不3着",
    "shogai_furyo_4chaku": "障不4着",
    "shogai_furyo_5chaku": "障不5着",
    "shogai_furyo_chakugai": "障不着外",
    "shiba_short_1chaku": "芝16下1着",
    "shiba_short_2chaku": "芝16下2着",
    "shiba_short_3chaku": "芝16下3着",
    "shiba_short_4chaku": "芝16下4着",
    "shiba_short_5chaku": "芝16下5着",
    "shiba_short_chakugai": "芝16下着外",
    "shiba_middle_1chaku": "芝22下1着",
    "shiba_middle_2chaku": "芝22下2着",
    "shiba_middle_3chaku": "芝22下3着",
    "shiba_middle_4chaku": "芝22下4着",
    "shiba_middle_5chaku": "芝22下5着",
    "shiba_middle_chakugai": "芝22下着外",
    "shiba_long_1chaku": "芝22超1着",
    "shiba_long_2chaku": "芝22超2着",
    "shiba_long_3chaku": "芝22超3着",
    "shiba_long_4chaku": "芝22超4着",
    "shiba_long_5chaku": "芝22超5着",
    "shiba_long_chakugai": "芝22超着外",
    "dirt_short_1chaku": "ダ16下1着",
    "dirt_short_2chaku": "ダ16下2着",
    "dirt_short_3chaku": "ダ16下3着",
    "dirt_short_4chaku": "ダ16下4着",
    "dirt_short_5chaku": "ダ16下5着",
    "dirt_short_chakugai": "ダ16下着外",
    "dirt_middle_1chaku": "ダ22下1着",
    "dirt_middle_2chaku": "ダ22下2着",
    "dirt_middle_3chaku": "ダ22下3着",
    "dirt_middle_4chaku": "ダ22下4着",
    "dirt_middle_5chaku": "ダ22下5着",
    "dirt_middle_chakugai": "ダ22下着外",
    "dirt_long_1chaku": "ダ22超1着",
    "dirt_long_2chaku": "ダ22超2着",
    "dirt_long_3chaku": "ダ22超3着",
    "dirt_long_4chaku": "ダ22超4着",
    "dirt_long_5chaku": "ダ22超5着",
    "dirt_long_chakugai": "ダ22超着外",
    "kyakushitsu_keiko_nige": "脚質傾向逃げ",
    "kyakushitsu_keiko_senko": "脚質傾向先行",
    "kyakushitsu_keiko_sashi": "脚質傾向差し",
    "kyakushitsu_keiko_oikomi": "脚質傾向追込",
    "toroku_race_su": "登録レース数",
}


def convert_horse_master(raw: pd.DataFrame) -> pd.DataFrame:
    """KYOSOBA_MASTER2出力を統一スキーマに変換する.

    Args:
        raw (pd.DataFrame): MasterGetter.get_kyosoba_master2()の出力（convert_codes=False）

    Returns:
        pd.DataFrame: 統一スキーマに変換されたDataFrame（HORSE_MASTER_COLUMNSのカラム、1行）
    """
    if raw.empty:
        return apply_types(ensure_columns(pd.DataFrame(), HORSE_MASTER_COLUMNS), HORSE_MASTER_TYPES)

    row = raw.iloc[0].to_dict()
    converted: dict[str, object] = {}
    for raw_col, ja_col in _COLUMN_MAP.items():
        val = row.get(raw_col, pd.NA)
        if isinstance(val, float) and pd.isna(val):
            converted[ja_col] = pd.NA
        elif ja_col == "馬主名" and isinstance(val, str):
            converted[ja_col] = val.replace("　", "").strip()
        else:
            converted[ja_col] = val

    df = pd.DataFrame([converted])
    return apply_types(ensure_columns(df, HORSE_MASTER_COLUMNS), HORSE_MASTER_TYPES)
