name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ci:
    uses: KeibaAI-developer/library-workflow/.github/workflows/ci.yml@main
    with:
      package_name: keiba_data_interface
      repo_name: keiba-data-interface
      run_integration_test: true
      dependency_library: 'keiba-scraping mykeibadb-python'
